<a href="https://colab.research.google.com/github/haiderfarooq3/AI_Lab02/blob/main/i221943_AI_Lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TASK ONE:**


In [22]:
import pandas as pd

file_path = "vgsalesGlobale.csv"
df = pd.read_csv(file_path)

total_global_sales = df["Global_Sales"].sum()
highest_global_sales_game = df.loc[df["Global_Sales"].idxmax(), ["Name", "Global_Sales"]]
average_sales_per_region = df[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].mean()
top_5_genres = df.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False).head(5)
genre_sales_by_region = df.groupby("Genre")[["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]].sum()
most_popular_genre_na = genre_sales_by_region["NA_Sales"].idxmax()
last_10_rows = df.tail(10)
top_3_platforms = df.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False).head(3)
market_share_per_genre = (df.groupby("Genre")["Global_Sales"].sum() / total_global_sales) * 100
correlation_na_eu = df["NA_Sales"].corr(df["EU_Sales"])

print("Total Global Sales:", total_global_sales)
print("\nGame with Highest Global Sales:", highest_global_sales_game["Name"], "-", highest_global_sales_game["Global_Sales"], "M")
print("\nAverage Sales per Region:\n", average_sales_per_region)
print("\nTop 5 Most Popular Genres:\n", top_5_genres)
print("\nTotal Sales for Each Genre in Each Region:\n", genre_sales_by_region)
print("\nMost Popular Genre in NA:", most_popular_genre_na)
print("\nLast 10 Rows of the Dataset:\n", last_10_rows)
print("\nTop 3 Gaming Platforms by Global Sales:\n", top_3_platforms)
print("\nMarket Share of Each Genre (% of Global Sales):\n", market_share_per_genre)
print("\nCorrelation Coefficient between NA Sales & EU Sales:", correlation_na_eu)


Total Global Sales: 8920.44

Game with Highest Global Sales: Wii Sports - 82.74 M

Average Sales per Region:
 NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

Top 5 Most Popular Genres:
 Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

Total Sales for Each Genre in Each Region:
               NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.

# **TASK TWO:**

In [23]:
dictionary = {
    "hello": "hola",
    "goodbye": "adiós",
    "please": "por favor",
    "thank you": "gracias",
    "sorry": "lo siento",
    "one": "uno",
    "two": "dos",
    "three": "tres",
    "four": "cuatro",
    "five": "cinco",
    "six": "seis",
    "seven": "siete",
    "eight": "ocho",
    "nine": "nueve",
    "ten": "diez",
}

while True:
    word = input("Enter an English word (or type 'exit' to quit): ").strip().lower()

    if word == "exit":
        print("Goodbye!")
        break

    if word in dictionary:
        print(f"The Spanish translation of '{word}' is '{dictionary[word]}'.")
    else:
        print(f"Sorry, the translation for '{word}' is not available.")


Enter an English word (or type 'exit' to quit): one
The Spanish translation of 'one' is 'uno'.
Enter an English word (or type 'exit' to quit): hello
The Spanish translation of 'hello' is 'hola'.
Enter an English word (or type 'exit' to quit): exit
Goodbye!


# **TASK THREE:**

In [24]:
def classify_emails(emails):
    important_keywords = ["meeting", "schedule", "urgent", "project", "deadline", "invoice", "appointment"]
    promotions_keywords = ["sale", "discount", "offer", "deal", "limited time", "buy now", "promo"]
    spam_keywords = ["winner", "prize", "lottery", "free money", "urgent action required", "click here", "unsubscribe"]

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        email_lower = email.lower()
        if any(keyword in email_lower for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in email_lower for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in email_lower for keyword in spam_keywords):
            spam_emails.append(email)
        else:
            important_emails.append(email)

    return important_emails, promotions_emails, spam_emails


emails_list = [
    "Your meeting is scheduled for tomorrow at 10 AM.",
    "Limited time offer! Buy one get one free on all products.",
    "Congratulations! You are a winner of our lottery prize.",
    "Urgent: Please review the project deadline updates.",
    "Big discount on electronics, shop now!",
    "Invoice for your recent purchase is attached.",
    "Click here to claim your free money!",
    "Appointment confirmation for your doctor's visit.",
    "You have been selected to receive a free prize!",
]

important, promotions, spam = classify_emails(emails_list)

print("Important Emails!!!:")
for email in important:
    print("-", email)

print("\n Promotions Emails:")
for email in promotions:
    print("-", email)

print("\n Spam Emails:")
for email in spam:
    print("-", email)


Important Emails!!!:
- Your meeting is scheduled for tomorrow at 10 AM.
- Urgent: Please review the project deadline updates.
- Invoice for your recent purchase is attached.
- Appointment confirmation for your doctor's visit.

 Promotions Emails:
- Limited time offer! Buy one get one free on all products.
- Big discount on electronics, shop now!

 Spam Emails:
- Congratulations! You are a winner of our lottery prize.
- Click here to claim your free money!
- You have been selected to receive a free prize!


# **TASK FOUR:**

In [25]:
products = {
    1: "AI Response Simulator",
    2: "Investment Decision",
    3: "Market Analysis Tool"
}

shopping_cart = []

print("Welcome to the Online Store!")
print("Available products:")
for key, value in products.items():
    print(f"{key}. {value}")

while True:
    choice = input("\nEnter the number of the product to add to the cart (or 'q' to checkout): ").strip().lower()

    if choice == 'q':
        break

    if not choice.isdigit():
        print("Invalid input! Please enter a valid number.")
        continue

    choice = int(choice)

    if choice in products:
        shopping_cart.append(products[choice])
        print(f" '{products[choice]}' has been added to your cart.")
    else:
        print(" Invalid choice! Please select a valid product number.")

print("\n Your Shopping Cart:")
if shopping_cart:
    for item in shopping_cart:
        print("-", item)
else:
    print("Your cart is empty.")

print("\n Thank you for shopping with us!")


Welcome to the Online Store!
Available products:
1. AI Response Simulator
2. Investment Decision
3. Market Analysis Tool

Enter the number of the product to add to the cart (or 'q' to checkout): 3
 'Market Analysis Tool' has been added to your cart.

Enter the number of the product to add to the cart (or 'q' to checkout): 2
 'Investment Decision' has been added to your cart.

Enter the number of the product to add to the cart (or 'q' to checkout): Q

 Your Shopping Cart:
- Market Analysis Tool
- Investment Decision

 Thank you for shopping with us! Goodbye! 👋


# **TASK FIVE:**

In [26]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

addition_result = array1 + array2
product_result = array1 * array2

print("Element-wise Addition:\n", addition_result)
print("\nElement-wise Product:\n", product_result)


Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Product:
 [[ 7 16 27]
 [40 55 72]]


# **TASK SIX:**

In [27]:
import numpy as np

array_1d = np.arange(12)

array_2d = array_1d.reshape(3, 4)

array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_b = np.array([[7, 8, 9], [10, 11, 12]])

concatenated_horizontally = np.hstack((array_a, array_b))
concatenated_vertically = np.vstack((array_a, array_b))

print("Reshaped 2D Array (3×4):\n", array_2d)
print("\nConcatenated Horizontally:\n", concatenated_horizontally)
print("\nConcatenated Vertically:\n", concatenated_vertically)


Reshaped 2D Array (3×4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Concatenated Horizontally:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Concatenated Vertically:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# **TASK SEVEN:**

In [28]:
my_list = [1, 2, 3, 4, 5]
reversed_list = my_list[::-1]

print("Original List:", my_list)
print("Reversed List:", reversed_list)


Original List: [1, 2, 3, 4, 5]
Reversed List: [5, 4, 3, 2, 1]
